package match_test

// commonMisspellings pairs a misspelling with the word intended. They are
// drawn from the usual lists of frequently misspelled English words, chosen so
// that every correction exists in /usr/share/dict/words.
//
// Entries whose misspelling is itself a real word (calender, wich, dose) are
// deliberately absent: those resolve as exact matches and measure nothing.
var commonMisspellings = []struct{ wrong, right string }{
	{"recieve", "receive"},
	{"seperate", "separate"},
	{"definately", "definitely"},
	{"occurence", "occurrence"},
	{"acheive", "achieve"},
	{"wierd", "weird"},
	{"accomodate", "accommodate"},
	{"embarass", "embarrass"},
	{"concious", "conscious"},
	{"neccessary", "necessary"},
	{"goverment", "government"},
	{"publically", "publicly"},
	{"arguement", "argument"},
	{"begining", "beginning"},
	{"beleive", "believe"},
	{"buisness", "business"},
	{"cemetary", "cemetery"},
	{"changable", "changeable"},
	{"collegue", "colleague"},
	{"comming", "coming"},
	{"commitee", "committee"},
	{"completly", "completely"},
	{"curiousity", "curiosity"},
	{"dilemna", "dilemma"},
	{"dissapear", "disappear"},
	{"dissapoint", "disappoint"},
	{"enviroment", "environment"},
	{"existance", "existence"},
	{"familier", "familiar"},
	{"finaly", "finally"},
	{"foriegn", "foreign"},
	{"freind", "friend"},
	{"gaurd", "guard"},
	{"glamourous", "glamorous"},
	{"gratefull", "grateful"},
	{"independant", "independent"},
	{"occassion", "occasion"},
	{"persistant", "persistent"},
	{"priviledge", "privilege"},
	{"recomend", "recommend"},
	{"relevent", "relevant"},
	{"religous", "religious"},
	{"rythm", "rhythm"},
	{"seige", "siege"},
	{"succesful", "successful"},
	{"supercede", "supersede"},
	{"tommorow", "tomorrow"},
	{"tounge", "tongue"},
	{"truely", "truly"},
	{"untill", "until"},
	{"writting", "writing"},
	{"occurance", "occurrence"},
	{"threshhold", "threshold"},
	{"noticable", "noticeable"},
	{"maintainance", "maintenance"},
	{"perseverence", "perseverance"},
	{"questionaire", "questionnaire"},
	{"millenium", "millennium"},
	{"mispell", "misspell"},
	{"pavillion", "pavilion"},
}
